---
spring:
  profiles:
    group:
      local: common, locdb, loc
      dev: common, devdb, develop
      prod: common
---
spring:
  config:
    activate:
      on-profile: common
  pid:
    file: ./pid/hypergitPortal.pid
  mail:
    host: smtp.gmail.com
    port: 587
    username: 'rockgis@gmail.com'
    password: 'dldPwns!@09'
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  jpa:
    hibernate:
      connection:
        provider_class: com.zaxxer.hikari.hibernate.HikariConnectionProvider
      naming:
        physical-strategy:  org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
  datasource:
    hikari:
      type: com.zaxxer.hikari.HikariDataSource
      idle-timeout: 10000
      maximum-pool-size: 10
      minimum-idle: 5

server:
  servlet:
    session:
      #      session delete when app restart
      persistent: false
      cookie:
        name: hypergit
        max-age: 3660
        http-only: true
  tomcat:
    basedir: .
    accesslog:
      enabled: true
      directory: logs
      prefix: access_log
      buffered: false
      suffix: .log
      file-date-format: .yyyy-MM-dd
  error:
    include-exception: true # 오류 응답에 exception의 내용을 포함할지 여부
    include-stacktrace: always # 오류 응답에 stacktrace 내용을 포함할 지 여부

logging:
  level:
    root: info
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
    com.zaxxer.hikari.HikariConfig: DEBUG
    com.zaxxer.hikari: trace
    org.thymeleaf: info

authentication:
  localAuth: /admin
  saml:
    entity-id: hypergitSaml
    ipd-url: http://localhost:9090/sso
    acs: /acs
    acsUrl: http://${server.address}:${server.port}
---
spring:
  config:
    activate:
      on-profile: production

---
spring:
  config:
    activate:
      on-profile: loc

server:
  port: 9091
  tomcat:
    accesslog:
      enabled: true
      directory: /dev
      prefix: stdout
      buffered: false
      suffix: ""
      file-date-format: ""
  address: 127.0.0.1

---
spring:
  config:
    activate:
      on-profile: develop
  security:
    saml2:
      relyingparty:
        registration:
          hypergitsaml:
#            signing:
#              credentials:
#                - private-key-location: "classpath:credentials/private.key"
#                  certificate-location: "classpath:credentials/public.cer"
            identityprovider:
              entity-id: hypergitSaml
              singlesignon:
                sign-request: false
                url: http://localhost:9091/sso
              metadata-uri: http://localhost:8081/sample-idp/saml/idp/metadata
server:
  port: 9091
  tomcat:
    accesslog:
      enabled: false
      directory: /dev
      prefix: stdout
      buffered: false
      suffix: ""
      file-date-format: ""
#  address: 10.11.10.200
---
spring:
  config:
    activate:
      on-profile: locdb
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hypergit?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: dldPwns!@09

---
spring:
  config:
    activate:
      on-profile: devdb
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.200.101.15:3307/hypergit?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: rockgis
    password: dldPwns!@09
---
spring:
  config:
    activate:
      on-profile: h2db
  datasource:
    url: jdbc:h2:mem:test
    username: rockgis
    password: dldPwns!@09
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
